version: "3"
services:
  graphql-app:
    container_name: app
    build: ../
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      postgres:
        condition: service_started
    env_file:
      - .env